### PR TITLE
Implemented Binary Search Algorithm

### PR DESCRIPTION
**Pull request by LukaJaj**

### CODE REVIEW

**Comment by LukaJaj** [comment]
@frextrite could you explain me in more details how can i do this?

**Comment by LukaJaj** [comment]
@frextrite If its possible could you do it with yourself and just merge the pr?

**Comment by LukaJaj** [comment]
@frextrite I changed name from --amend as you wanted

**Comment by frextrite** [comment]
Right on track! Merging.

**Pull request merged**
